name: Deploy to Amazon ECS

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: barrel-api
  ECS_SERVICE: "workflows-api-dev-service"
  ECS_CLUSTER: "barrel2-dev-cluster"
  CONTAINER_NAME: "workflows-api-service"
  TASK_FAMILY_NAME: "workflows-api-dev-task"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version from pyproject.toml
        id: version
        run: |
          VERSION=$(grep -oP '(?<=^version = ")[^"]*' pyproject.toml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configure Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        if: steps.login-ecr.outcome == 'success'
        id: build-image
        run: |
          docker build -t ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/${{env.ECR_REPOSITORY}}:${{ env.VERSION }} .

      - name: Push Docker image
        id: push-image
        if: steps.build-image.outcome == 'success'
        run: |
          docker push ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/${{env.ECR_REPOSITORY}}:${{ env.VERSION }}

      - name: Create Git Tag
        if: steps.push-image.outcome == 'success'
        run: |
          git tag -a "${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
          git push origin "${{ env.VERSION }}"

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{env.TASK_FAMILY_NAME}} --query taskDefinition > task-definition.json

      - name: Fill in new image ID in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{env.CONTAINER_NAME}}
          image: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/${{env.ECR_REPOSITORY}}:${{ env.VERSION }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Sync to S3
        run:  |
              a=$(date +%Y%m%d%H%M%S).zip
              zip -r $a . -x '/.git*' '/.github/*' '/aws/*' '/awscliv2.zip*'
              aws s3 sync . ${{ secrets.BACKUP_S3_BUCKET}} --exclude "*" --include "$a"
